---
# tasks file for lighthouse_role2
- name: Install nginx
  become: true
  apt: 
    name: nginx
    state: latest
  notify: nginx-start
  
- name: Add domain
  become: true
  template:
    src: lighthouse_nginx.j2
    dest: /etc/nginx/sites-enabled/default 
       
- name: Install lighthouse
  ansible.builtin.get_url:
    url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
    dest: "inst_file/master.zip"
    mode: 0644

- name: Creating directory
  become: true
  file:
   path: "/opt/lighthouse"
   state: directory
   mode: 0777

- name: Extract lighthouse
  become: true
  unarchive:
    remote_src: yes 
    src: "{{ lightdir }}/master.zip"
    dest: "/opt/lighthouse"

  notify: nginx-reload
  
